import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BookOpen, Plus, Search, Pencil, Trash2, Brain, EyeOff, Eye, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useCurrentUser } from "@/lib/useCurrentUser";
import { createKnowledgeItem, deleteKnowledgeItem, listKnowledgeItems, updateKnowledgeItem, type KnowledgeItem } from "@/lib/operations";

const KNOWLEDGE_SECTORS = ["Todos", "CFTV", "Vigilância", "Portaria", "Ronda", "Operações", "Administrativo"] as const;

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl ${className}`} style={{ background: "var(--bg-surface)", border: "1px solid var(--border)", boxShadow: "var(--shadow-card, var(--shadow-md))" }}>{children}</div>; }

export function KnowledgeWorkspace({ searchMode = false }: { searchMode?: boolean }) {
  const qc = useQueryClient(); const { data: user } = useCurrentUser(); const isAdmin = user?.isAdmin ?? false;
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("Todos"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<KnowledgeItem | null>(null); const [expanded, setExpanded] = useState<string | null>(null);
  const [form, setForm] = useState({ title:"", category:"Geral", content:"", target_sector:"Todos" });
  const query = useQuery({ queryKey:["knowledge-items"], queryFn:listKnowledgeItems }); const rows = query.data ?? [];
  const categories = ["Todos", ...Array.from(new Set(rows.map((r) => r.category))).sort()];
  const filtered = useMemo(() => rows.filter((r) => { if (category !== "Todos" && r.category !== category) return false; const q = search.toLowerCase().trim(); return !q || [r.title,r.category,r.content,r.target_sector].some((v) => v.toLowerCase().includes(q)); }), [rows, search, category]);
  const reset = () => setForm({ title:"", category:"Geral", content:"", target_sector:"Todos" });
  const invalidate = () => qc.invalidateQueries({queryKey:["knowledge-items"]});
  const save = useMutation({ mutationFn: async () => { if (!form.title.trim() || !form.content.trim()) throw new Error("Informe título e conteúdo"); if (editing) await updateKnowledgeItem(editing.id, form); else await createKnowledgeItem(form); }, onSuccess:async () => { toast.success(editing ? "Conteúdo atualizado" : "Conteúdo criado"); setOpen(false); setEditing(null); reset(); await invalidate(); }, onError:(e:Error)=>toast.error(e.message) });
  const remove = useMutation({ mutationFn:deleteKnowledgeItem, onSuccess:async ()=>{toast.success("Conteúdo excluído"); await invalidate();}, onError:(e:Error)=>toast.error(e.message)});
  const toggle = useMutation({ mutationFn:(item:KnowledgeItem)=>updateKnowledgeItem(item.id,{active:!item.active}), onSuccess:async()=>{toast.success("Situação do conteúdo atualizada"); await invalidate();}, onError:(e:Error)=>toast.error(e.message)});
  const openEdit = (r:KnowledgeItem) => { setEditing(r); setForm({title:r.title,category:r.category,content:r.content,target_sector:r.target_sector}); setOpen(true); };

  if (query.isLoading) return <div className="flex justify-center py-20"><div className="h-8 w-8 animate-spin rounded-full border-4" style={{borderColor:"var(--border)",borderTopColor:"#C8102E"}} /></div>;
  if (query.isError) return <Card className="mx-auto max-w-xl p-8 text-center"><AlertTriangle className="mx-auto h-9 w-9 text-amber-500"/><p className="mt-3 font-black" style={{color:"var(--text-1)"}}>Não foi possível carregar os conteúdos.</p><p className="mt-1 text-sm" style={{color:"var(--text-4)"}}>Tente novamente. Se o problema persistir, informe a Inspetoria.</p><Button variant="outline" className="mt-4" onClick={()=>query.refetch()}><RefreshCw className="mr-2 h-4 w-4"/> Tentar novamente</Button></Card>;

  return <div className="mx-auto max-w-6xl space-y-5 pb-10"><div className="rounded-[1.5rem] p-5 md:p-6 flex flex-col md:flex-row md:items-end md:justify-between gap-4" style={{background:"linear-gradient(135deg,#171118,#2b0b13 50%,#111216)",border:"1px solid rgba(200,16,46,.26)"}}><div><div className="flex items-center gap-2 text-[11px] uppercase tracking-[.2em] font-black text-white/40">{searchMode ? <Brain className="w-4 h-4"/> : <BookOpen className="w-4 h-4"/>} Conhecimento operacional</div><h1 className="mt-2 text-2xl md:text-3xl font-black text-white">{searchMode ? "IA Base" : "Conteúdos"}</h1><p className="mt-1 text-sm text-white/50">{searchMode ? "Pesquise rapidamente procedimentos e conteúdos cadastrados." : "Biblioteca central de procedimentos, treinamentos e referências."}</p></div>{isAdmin && <Button onClick={()=>{setEditing(null);reset();setOpen(true)}} className="bg-[#C8102E] hover:bg-[#A00D24] text-white"><Plus className="w-4 h-4 mr-2"/> Novo conteúdo</Button>}</div>
    <Card className="p-4"><div className="grid md:grid-cols-[1fr_200px] gap-3"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" style={{color:"var(--text-4)"}}/><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar por título, palavra-chave, setor ou conteúdo..." className="pl-10"/></div><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.map((c)=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div></Card>
    <div className="grid gap-3 md:grid-cols-2">{filtered.map((r)=><Card key={r.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-bold" style={{color:"var(--text-1)"}}>{r.title}</p>{!r.active && <span className="text-[10px] font-black text-amber-500">INATIVO</span>}</div><p className="mt-1 text-xs" style={{color:"var(--text-4)"}}>{r.category} · {r.target_sector}</p></div>{isAdmin && <div className="flex gap-1"><Button size="icon" variant="ghost" disabled={toggle.isPending} onClick={()=>toggle.mutate(r)} aria-label={r.active?"Desativar conteúdo":"Ativar conteúdo"}>{r.active?<Eye className="w-4 h-4"/>:<EyeOff className="w-4 h-4"/>}</Button><Button size="icon" variant="ghost" onClick={()=>openEdit(r)} aria-label="Editar conteúdo"><Pencil className="w-4 h-4"/></Button><Button size="icon" variant="ghost" className="text-red-500" disabled={remove.isPending} onClick={()=>{if(confirm(`Excluir o conteúdo “${r.title}”?`)) remove.mutate(r.id)}} aria-label="Excluir conteúdo"><Trash2 className="w-4 h-4"/></Button></div>}</div><p className={`mt-3 text-sm whitespace-pre-wrap ${expanded===r.id?"":"line-clamp-5"}`} style={{color:"var(--text-2)"}}>{r.content}</p>{r.content.length>260 && <button className="mt-2 text-xs font-bold" style={{color:"var(--accent)"}} onClick={()=>setExpanded(expanded===r.id?null:r.id)}>{expanded===r.id?"Mostrar menos":"Ler completo"}</button>}</Card>)}{!filtered.length&&<Card className="p-10 text-center md:col-span-2"><BookOpen className="w-10 h-10 mx-auto opacity-30" style={{color:"var(--text-4)"}}/><p className="mt-3 font-bold" style={{color:"var(--text-1)"}}>Nenhum conteúdo encontrado.</p></Card>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-2xl max-h-[92vh] overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Editar conteúdo":"Novo conteúdo"}</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-1.5"><Label>Título *</Label><Input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></div><div className="grid md:grid-cols-2 gap-3"><div className="space-y-1.5"><Label>Categoria</Label><Input value={form.category} onChange={(e)=>setForm({...form,category:e.target.value})}/></div><div className="space-y-1.5"><Label>Setor-alvo</Label><Select value={form.target_sector} onValueChange={(v)=>setForm({...form,target_sector:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{KNOWLEDGE_SECTORS.map((s)=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></div><div className="space-y-1.5"><Label>Conteúdo *</Label><textarea value={form.content} onChange={(e)=>setForm({...form,content:e.target.value})} className="w-full min-h-60 rounded-xl p-3 text-sm" style={{background:"var(--bg-surface-2)",border:"1px solid var(--border)",color:"var(--text-1)"}}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={()=>save.mutate()} disabled={save.isPending} className="bg-[#C8102E] hover:bg-[#A00D24] text-white">{save.isPending?"Salvando...":"Salvar"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}