/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAssinaturasProvasRouteImport } from './routes/_authenticated/assinaturas-provas'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAvaliacaoPraticaRouteImport } from './routes/_authenticated/avaliacao-pratica'
import { Route as AuthenticatedBancoQuestoesRouteImport } from './routes/_authenticated/banco-questoes'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedCiclosTreinamentoRouteImport } from './routes/_authenticated/ciclos-treinamento'
import { Route as AuthenticatedConteudosRouteImport } from './routes/_authenticated/conteudos'
import { Route as AuthenticatedCronogramaRouteImport } from './routes/_authenticated/cronograma'
import { Route as AuthenticatedCronogramaGestaoRouteImport } from './routes/_authenticated/cronograma-gestao'
import { Route as AuthenticatedDesafioDiarioRouteImport } from './routes/_authenticated/desafio-diario'
import { Route as AuthenticatedDocumentoSegurancaRouteImport } from './routes/_authenticated/documento-seguranca'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFocoRouteImport } from './routes/_authenticated/foco'
import { Route as AuthenticatedIaBaseRouteImport } from './routes/_authenticated/ia-base'
import { Route as AuthenticatedIndividualRouteImport } from './routes/_authenticated/individual'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedMinhasOcorrenciasRouteImport } from './routes/_authenticated/minhas-ocorrencias'
import { Route as AuthenticatedModulosTreinamentoRouteImport } from './routes/_authenticated/modulos-treinamento'
import { Route as AuthenticatedOcorrenciasRouteImport } from './routes/_authenticated/ocorrencias'
import { Route as AuthenticatedOportunidadesRouteImport } from './routes/_authenticated/oportunidades'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedPraticoRouteImport } from './routes/_authenticated/pratico'
import { Route as AuthenticatedProgressoRouteImport } from './routes/_authenticated/progresso'
import { Route as AuthenticatedProvaRealizarRouteImport } from './routes/_authenticated/prova-realizar'
import { Route as AuthenticatedProvasRouteImport } from './routes/_authenticated/provas'
import { Route as AuthenticatedProvasCriarRouteImport } from './routes/_authenticated/provas-criar'
import { Route as AuthenticatedRadarAnalisesRouteImport } from './routes/_authenticated/radar-analises'
import { Route as AuthenticatedRelatorioMensalRouteImport } from './routes/_authenticated/relatorio-mensal'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedResumosRouteImport } from './routes/_authenticated/resumos'
import { Route as AuthenticatedRiscoRouteImport } from './routes/_authenticated/risco'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as AuthenticatedStressTestRouteImport } from './routes/_authenticated/stress-test'
import { Route as AuthenticatedTesteRapidoRouteImport } from './routes/_authenticated/teste-rapido'
import { Route as AuthenticatedTreinamentosRouteImport } from './routes/_authenticated/treinamentos'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as AuthenticatedValidarCertificadosRouteImport } from './routes/_authenticated/validar-certificados'
import { Route as AuthenticatedCertificadoAttemptIdRouteImport } from './routes/_authenticated/certificado.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturasProvasRoute =
  AuthenticatedAssinaturasProvasRouteImport.update({
    id: '/assinaturas-provas',
    path: '/assinaturas-provas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacaoPraticaRoute =
  AuthenticatedAvaliacaoPraticaRouteImport.update({
    id: '/avaliacao-pratica',
    path: '/avaliacao-pratica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBancoQuestoesRoute =
  AuthenticatedBancoQuestoesRouteImport.update({
    id: '/banco-questoes',
    path: '/banco-questoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCiclosTreinamentoRoute =
  AuthenticatedCiclosTreinamentoRouteImport.update({
    id: '/ciclos-treinamento',
    path: '/ciclos-treinamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConteudosRoute = AuthenticatedConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramaRoute = AuthenticatedCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCronogramaGestaoRoute =
  AuthenticatedCronogramaGestaoRouteImport.update({
    id: '/cronograma-gestao',
    path: '/cronograma-gestao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDesafioDiarioRoute =
  AuthenticatedDesafioDiarioRouteImport.update({
    id: '/desafio-diario',
    path: '/desafio-diario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentoSegurancaRoute =
  AuthenticatedDocumentoSegurancaRouteImport.update({
    id: '/documento-seguranca',
    path: '/documento-seguranca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFocoRoute = AuthenticatedFocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaBaseRoute = AuthenticatedIaBaseRouteImport.update({
  id: '/ia-base',
  path: '/ia-base',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndividualRoute = AuthenticatedIndividualRouteImport.update({
  id: '/individual',
  path: '/individual',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasOcorrenciasRoute =
  AuthenticatedMinhasOcorrenciasRouteImport.update({
    id: '/minhas-ocorrencias',
    path: '/minhas-ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModulosTreinamentoRoute =
  AuthenticatedModulosTreinamentoRouteImport.update({
    id: '/modulos-treinamento',
    path: '/modulos-treinamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOcorrenciasRoute =
  AuthenticatedOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOportunidadesRoute =
  AuthenticatedOportunidadesRouteImport.update({
    id: '/oportunidades',
    path: '/oportunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPraticoRoute = AuthenticatedPraticoRouteImport.update({
  id: '/pratico',
  path: '/pratico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressoRoute = AuthenticatedProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvaRealizarRoute =
  AuthenticatedProvaRealizarRouteImport.update({
    id: '/prova-realizar',
    path: '/prova-realizar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProvasRoute = AuthenticatedProvasRouteImport.update({
  id: '/provas',
  path: '/provas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvasCriarRoute =
  AuthenticatedProvasCriarRouteImport.update({
    id: '/provas-criar',
    path: '/provas-criar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadarAnalisesRoute =
  AuthenticatedRadarAnalisesRouteImport.update({
    id: '/radar-analises',
    path: '/radar-analises',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatorioMensalRoute =
  AuthenticatedRelatorioMensalRouteImport.update({
    id: '/relatorio-mensal',
    path: '/relatorio-mensal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumosRoute = AuthenticatedResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiscoRoute = AuthenticatedRiscoRouteImport.update({
  id: '/risco',
  path: '/risco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStressTestRoute = AuthenticatedStressTestRouteImport.update({
  id: '/stress-test',
  path: '/stress-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTesteRapidoRoute =
  AuthenticatedTesteRapidoRouteImport.update({
    id: '/teste-rapido',
    path: '/teste-rapido',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreinamentosRoute =
  AuthenticatedTreinamentosRouteImport.update({
    id: '/treinamentos',
    path: '/treinamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValidarCertificadosRoute =
  AuthenticatedValidarCertificadosRouteImport.update({
    id: '/validar-certificados',
    path: '/validar-certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificadoAttemptIdRoute =
  AuthenticatedCertificadoAttemptIdRouteImport.update({
    id: '/certificado/$attemptId',
    path: '/certificado/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assinaturas-provas': typeof AuthenticatedAssinaturasProvasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/avaliacao-pratica': typeof AuthenticatedAvaliacaoPraticaRoute
  '/banco-questoes': typeof AuthenticatedBancoQuestoesRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/ciclos-treinamento': typeof AuthenticatedCiclosTreinamentoRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/cronograma-gestao': typeof AuthenticatedCronogramaGestaoRoute
  '/desafio-diario': typeof AuthenticatedDesafioDiarioRoute
  '/documento-seguranca': typeof AuthenticatedDocumentoSegurancaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/foco': typeof AuthenticatedFocoRoute
  '/ia-base': typeof AuthenticatedIaBaseRoute
  '/individual': typeof AuthenticatedIndividualRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/minhas-ocorrencias': typeof AuthenticatedMinhasOcorrenciasRoute
  '/modulos-treinamento': typeof AuthenticatedModulosTreinamentoRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/pratico': typeof AuthenticatedPraticoRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/prova-realizar': typeof AuthenticatedProvaRealizarRoute
  '/provas': typeof AuthenticatedProvasRoute
  '/provas-criar': typeof AuthenticatedProvasCriarRoute
  '/radar-analises': typeof AuthenticatedRadarAnalisesRoute
  '/relatorio-mensal': typeof AuthenticatedRelatorioMensalRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resumos': typeof AuthenticatedResumosRoute
  '/risco': typeof AuthenticatedRiscoRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/stress-test': typeof AuthenticatedStressTestRoute
  '/teste-rapido': typeof AuthenticatedTesteRapidoRoute
  '/treinamentos': typeof AuthenticatedTreinamentosRoute
  '/tv': typeof AuthenticatedTvRoute
  '/validar-certificados': typeof AuthenticatedValidarCertificadosRoute
  '/certificado/$attemptId': typeof AuthenticatedCertificadoAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/assinaturas-provas': typeof AuthenticatedAssinaturasProvasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/avaliacao-pratica': typeof AuthenticatedAvaliacaoPraticaRoute
  '/banco-questoes': typeof AuthenticatedBancoQuestoesRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/ciclos-treinamento': typeof AuthenticatedCiclosTreinamentoRoute
  '/conteudos': typeof AuthenticatedConteudosRoute
  '/cronograma': typeof AuthenticatedCronogramaRoute
  '/cronograma-gestao': typeof AuthenticatedCronogramaGestaoRoute
  '/desafio-diario': typeof AuthenticatedDesafioDiarioRoute
  '/documento-seguranca': typeof AuthenticatedDocumentoSegurancaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/foco': typeof AuthenticatedFocoRoute
  '/ia-base': typeof AuthenticatedIaBaseRoute
  '/individual': typeof AuthenticatedIndividualRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/minhas-ocorrencias': typeof AuthenticatedMinhasOcorrenciasRoute
  '/modulos-treinamento': typeof AuthenticatedModulosTreinamentoRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/pratico': typeof AuthenticatedPraticoRoute
  '/progresso': typeof AuthenticatedProgressoRoute
  '/prova-realizar': typeof AuthenticatedProvaRealizarRoute
  '/provas': typeof AuthenticatedProvasRoute
  '/provas-criar': typeof AuthenticatedProvasCriarRoute
  '/radar-analises': typeof AuthenticatedRadarAnalisesRoute
  '/relatorio-mensal': typeof AuthenticatedRelatorioMensalRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/resumos': typeof AuthenticatedResumosRoute
  '/risco': typeof AuthenticatedRiscoRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/stress-test': typeof AuthenticatedStressTestRoute
  '/teste-rapido': typeof AuthenticatedTesteRapidoRoute
  '/treinamentos': typeof AuthenticatedTreinamentosRoute
  '/tv': typeof AuthenticatedTvRoute
  '/validar-certificados': typeof AuthenticatedValidarCertificadosRoute
  '/certificado/$attemptId': typeof AuthenticatedCertificadoAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/assinaturas-provas': typeof AuthenticatedAssinaturasProvasRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/avaliacao-pratica': typeof AuthenticatedAvaliacaoPraticaRoute
  '/_authenticated/banco-questoes': typeof AuthenticatedBancoQuestoesRoute
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/ciclos-treinamento': typeof AuthenticatedCiclosTreinamentoRoute
  '/_authenticated/conteudos': typeof AuthenticatedConteudosRoute
  '/_authenticated/cronograma': typeof AuthenticatedCronogramaRoute
  '/_authenticated/cronograma-gestao': typeof AuthenticatedCronogramaGestaoRoute
  '/_authenticated/desafio-diario': typeof AuthenticatedDesafioDiarioRoute
  '/_authenticated/documento-seguranca': typeof AuthenticatedDocumentoSegurancaRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/foco': typeof AuthenticatedFocoRoute
  '/_authenticated/ia-base': typeof AuthenticatedIaBaseRoute
  '/_authenticated/individual': typeof AuthenticatedIndividualRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/minhas-ocorrencias': typeof AuthenticatedMinhasOcorrenciasRoute
  '/_authenticated/modulos-treinamento': typeof AuthenticatedModulosTreinamentoRoute
  '/_authenticated/ocorrencias': typeof AuthenticatedOcorrenciasRoute
  '/_authenticated/oportunidades': typeof AuthenticatedOportunidadesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/pratico': typeof AuthenticatedPraticoRoute
  '/_authenticated/progresso': typeof AuthenticatedProgressoRoute
  '/_authenticated/prova-realizar': typeof AuthenticatedProvaRealizarRoute
  '/_authenticated/provas': typeof AuthenticatedProvasRoute
  '/_authenticated/provas-criar': typeof AuthenticatedProvasCriarRoute
  '/_authenticated/radar-analises': typeof AuthenticatedRadarAnalisesRoute
  '/_authenticated/relatorio-mensal': typeof AuthenticatedRelatorioMensalRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/resumos': typeof AuthenticatedResumosRoute
  '/_authenticated/risco': typeof AuthenticatedRiscoRoute
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
  '/_authenticated/stress-test': typeof AuthenticatedStressTestRoute
  '/_authenticated/teste-rapido': typeof AuthenticatedTesteRapidoRoute
  '/_authenticated/treinamentos': typeof AuthenticatedTreinamentosRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/_authenticated/validar-certificados': typeof AuthenticatedValidarCertificadosRoute
  '/_authenticated/certificado/$attemptId': typeof AuthenticatedCertificadoAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/admin'
    | '/analytics'
    | '/assinaturas-provas'
    | '/auditoria'
    | '/avaliacao-pratica'
    | '/banco-questoes'
    | '/certificados'
    | '/ciclos-treinamento'
    | '/conteudos'
    | '/cronograma'
    | '/cronograma-gestao'
    | '/desafio-diario'
    | '/documento-seguranca'
    | '/equipe'
    | '/foco'
    | '/ia-base'
    | '/individual'
    | '/meu-perfil'
    | '/minhas-ocorrencias'
    | '/modulos-treinamento'
    | '/ocorrencias'
    | '/oportunidades'
    | '/painel'
    | '/pendencias'
    | '/pratico'
    | '/progresso'
    | '/prova-realizar'
    | '/provas'
    | '/provas-criar'
    | '/radar-analises'
    | '/relatorio-mensal'
    | '/relatorios'
    | '/resumos'
    | '/risco'
    | '/simulador'
    | '/stress-test'
    | '/teste-rapido'
    | '/treinamentos'
    | '/tv'
    | '/validar-certificados'
    | '/certificado/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/admin'
    | '/analytics'
    | '/assinaturas-provas'
    | '/auditoria'
    | '/avaliacao-pratica'
    | '/banco-questoes'
    | '/certificados'
    | '/ciclos-treinamento'
    | '/conteudos'
    | '/cronograma'
    | '/cronograma-gestao'
    | '/desafio-diario'
    | '/documento-seguranca'
    | '/equipe'
    | '/foco'
    | '/ia-base'
    | '/individual'
    | '/meu-perfil'
    | '/minhas-ocorrencias'
    | '/modulos-treinamento'
    | '/ocorrencias'
    | '/oportunidades'
    | '/painel'
    | '/pendencias'
    | '/pratico'
    | '/progresso'
    | '/prova-realizar'
    | '/provas'
    | '/provas-criar'
    | '/radar-analises'
    | '/relatorio-mensal'
    | '/relatorios'
    | '/resumos'
    | '/risco'
    | '/simulador'
    | '/stress-test'
    | '/teste-rapido'
    | '/treinamentos'
    | '/tv'
    | '/validar-certificados'
    | '/certificado/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/acessos'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/assinaturas-provas'
    | '/_authenticated/auditoria'
    | '/_authenticated/avaliacao-pratica'
    | '/_authenticated/banco-questoes'
    | '/_authenticated/certificados'
    | '/_authenticated/ciclos-treinamento'
    | '/_authenticated/conteudos'
    | '/_authenticated/cronograma'
    | '/_authenticated/cronograma-gestao'
    | '/_authenticated/desafio-diario'
    | '/_authenticated/documento-seguranca'
    | '/_authenticated/equipe'
    | '/_authenticated/foco'
    | '/_authenticated/ia-base'
    | '/_authenticated/individual'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/minhas-ocorrencias'
    | '/_authenticated/modulos-treinamento'
    | '/_authenticated/ocorrencias'
    | '/_authenticated/oportunidades'
    | '/_authenticated/painel'
    | '/_authenticated/pendencias'
    | '/_authenticated/pratico'
    | '/_authenticated/progresso'
    | '/_authenticated/prova-realizar'
    | '/_authenticated/provas'
    | '/_authenticated/provas-criar'
    | '/_authenticated/radar-analises'
    | '/_authenticated/relatorio-mensal'
    | '/_authenticated/relatorios'
    | '/_authenticated/resumos'
    | '/_authenticated/risco'
    | '/_authenticated/simulador'
    | '/_authenticated/stress-test'
    | '/_authenticated/teste-rapido'
    | '/_authenticated/treinamentos'
    | '/_authenticated/tv'
    | '/_authenticated/validar-certificados'
    | '/_authenticated/certificado/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinaturas-provas': {
      id: '/_authenticated/assinaturas-provas'
      path: '/assinaturas-provas'
      fullPath: '/assinaturas-provas'
      preLoaderRoute: typeof AuthenticatedAssinaturasProvasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacao-pratica': {
      id: '/_authenticated/avaliacao-pratica'
      path: '/avaliacao-pratica'
      fullPath: '/avaliacao-pratica'
      preLoaderRoute: typeof AuthenticatedAvaliacaoPraticaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banco-questoes': {
      id: '/_authenticated/banco-questoes'
      path: '/banco-questoes'
      fullPath: '/banco-questoes'
      preLoaderRoute: typeof AuthenticatedBancoQuestoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclos-treinamento': {
      id: '/_authenticated/ciclos-treinamento'
      path: '/ciclos-treinamento'
      fullPath: '/ciclos-treinamento'
      preLoaderRoute: typeof AuthenticatedCiclosTreinamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conteudos': {
      id: '/_authenticated/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof AuthenticatedConteudosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma': {
      id: '/_authenticated/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AuthenticatedCronogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cronograma-gestao': {
      id: '/_authenticated/cronograma-gestao'
      path: '/cronograma-gestao'
      fullPath: '/cronograma-gestao'
      preLoaderRoute: typeof AuthenticatedCronogramaGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafio-diario': {
      id: '/_authenticated/desafio-diario'
      path: '/desafio-diario'
      fullPath: '/desafio-diario'
      preLoaderRoute: typeof AuthenticatedDesafioDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documento-seguranca': {
      id: '/_authenticated/documento-seguranca'
      path: '/documento-seguranca'
      fullPath: '/documento-seguranca'
      preLoaderRoute: typeof AuthenticatedDocumentoSegurancaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/foco': {
      id: '/_authenticated/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof AuthenticatedFocoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia-base': {
      id: '/_authenticated/ia-base'
      path: '/ia-base'
      fullPath: '/ia-base'
      preLoaderRoute: typeof AuthenticatedIaBaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/individual': {
      id: '/_authenticated/individual'
      path: '/individual'
      fullPath: '/individual'
      preLoaderRoute: typeof AuthenticatedIndividualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-ocorrencias': {
      id: '/_authenticated/minhas-ocorrencias'
      path: '/minhas-ocorrencias'
      fullPath: '/minhas-ocorrencias'
      preLoaderRoute: typeof AuthenticatedMinhasOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulos-treinamento': {
      id: '/_authenticated/modulos-treinamento'
      path: '/modulos-treinamento'
      fullPath: '/modulos-treinamento'
      preLoaderRoute: typeof AuthenticatedModulosTreinamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias': {
      id: '/_authenticated/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof AuthenticatedOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oportunidades': {
      id: '/_authenticated/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof AuthenticatedOportunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pratico': {
      id: '/_authenticated/pratico'
      path: '/pratico'
      fullPath: '/pratico'
      preLoaderRoute: typeof AuthenticatedPraticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progresso': {
      id: '/_authenticated/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof AuthenticatedProgressoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prova-realizar': {
      id: '/_authenticated/prova-realizar'
      path: '/prova-realizar'
      fullPath: '/prova-realizar'
      preLoaderRoute: typeof AuthenticatedProvaRealizarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provas': {
      id: '/_authenticated/provas'
      path: '/provas'
      fullPath: '/provas'
      preLoaderRoute: typeof AuthenticatedProvasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provas-criar': {
      id: '/_authenticated/provas-criar'
      path: '/provas-criar'
      fullPath: '/provas-criar'
      preLoaderRoute: typeof AuthenticatedProvasCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar-analises': {
      id: '/_authenticated/radar-analises'
      path: '/radar-analises'
      fullPath: '/radar-analises'
      preLoaderRoute: typeof AuthenticatedRadarAnalisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio-mensal': {
      id: '/_authenticated/relatorio-mensal'
      path: '/relatorio-mensal'
      fullPath: '/relatorio-mensal'
      preLoaderRoute: typeof AuthenticatedRelatorioMensalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumos': {
      id: '/_authenticated/resumos'
      path: '/resumos'
      fullPath: '/resumos'
      preLoaderRoute: typeof AuthenticatedResumosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risco': {
      id: '/_authenticated/risco'
      path: '/risco'
      fullPath: '/risco'
      preLoaderRoute: typeof AuthenticatedRiscoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stress-test': {
      id: '/_authenticated/stress-test'
      path: '/stress-test'
      fullPath: '/stress-test'
      preLoaderRoute: typeof AuthenticatedStressTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teste-rapido': {
      id: '/_authenticated/teste-rapido'
      path: '/teste-rapido'
      fullPath: '/teste-rapido'
      preLoaderRoute: typeof AuthenticatedTesteRapidoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinamentos': {
      id: '/_authenticated/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof AuthenticatedTreinamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/validar-certificados': {
      id: '/_authenticated/validar-certificados'
      path: '/validar-certificados'
      fullPath: '/validar-certificados'
      preLoaderRoute: typeof AuthenticatedValidarCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificado/$attemptId': {
      id: '/_authenticated/certificado/$attemptId'
      path: '/certificado/$attemptId'
      fullPath: '/certificado/$attemptId'
      preLoaderRoute: typeof AuthenticatedCertificadoAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAssinaturasProvasRoute: typeof AuthenticatedAssinaturasProvasRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAvaliacaoPraticaRoute: typeof AuthenticatedAvaliacaoPraticaRoute
  AuthenticatedBancoQuestoesRoute: typeof AuthenticatedBancoQuestoesRoute
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedCiclosTreinamentoRoute: typeof AuthenticatedCiclosTreinamentoRoute
  AuthenticatedConteudosRoute: typeof AuthenticatedConteudosRoute
  AuthenticatedCronogramaRoute: typeof AuthenticatedCronogramaRoute
  AuthenticatedCronogramaGestaoRoute: typeof AuthenticatedCronogramaGestaoRoute
  AuthenticatedDesafioDiarioRoute: typeof AuthenticatedDesafioDiarioRoute
  AuthenticatedDocumentoSegurancaRoute: typeof AuthenticatedDocumentoSegurancaRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFocoRoute: typeof AuthenticatedFocoRoute
  AuthenticatedIaBaseRoute: typeof AuthenticatedIaBaseRoute
  AuthenticatedIndividualRoute: typeof AuthenticatedIndividualRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedMinhasOcorrenciasRoute: typeof AuthenticatedMinhasOcorrenciasRoute
  AuthenticatedModulosTreinamentoRoute: typeof AuthenticatedModulosTreinamentoRoute
  AuthenticatedOcorrenciasRoute: typeof AuthenticatedOcorrenciasRoute
  AuthenticatedOportunidadesRoute: typeof AuthenticatedOportunidadesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedPraticoRoute: typeof AuthenticatedPraticoRoute
  AuthenticatedProgressoRoute: typeof AuthenticatedProgressoRoute
  AuthenticatedProvaRealizarRoute: typeof AuthenticatedProvaRealizarRoute
  AuthenticatedProvasRoute: typeof AuthenticatedProvasRoute
  AuthenticatedProvasCriarRoute: typeof AuthenticatedProvasCriarRoute
  AuthenticatedRadarAnalisesRoute: typeof AuthenticatedRadarAnalisesRoute
  AuthenticatedRelatorioMensalRoute: typeof AuthenticatedRelatorioMensalRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedResumosRoute: typeof AuthenticatedResumosRoute
  AuthenticatedRiscoRoute: typeof AuthenticatedRiscoRoute
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
  AuthenticatedStressTestRoute: typeof AuthenticatedStressTestRoute
  AuthenticatedTesteRapidoRoute: typeof AuthenticatedTesteRapidoRoute
  AuthenticatedTreinamentosRoute: typeof AuthenticatedTreinamentosRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
  AuthenticatedValidarCertificadosRoute: typeof AuthenticatedValidarCertificadosRoute
  AuthenticatedCertificadoAttemptIdRoute: typeof AuthenticatedCertificadoAttemptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAssinaturasProvasRoute: AuthenticatedAssinaturasProvasRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAvaliacaoPraticaRoute: AuthenticatedAvaliacaoPraticaRoute,
  AuthenticatedBancoQuestoesRoute: AuthenticatedBancoQuestoesRoute,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedCiclosTreinamentoRoute: AuthenticatedCiclosTreinamentoRoute,
  AuthenticatedConteudosRoute: AuthenticatedConteudosRoute,
  AuthenticatedCronogramaRoute: AuthenticatedCronogramaRoute,
  AuthenticatedCronogramaGestaoRoute: AuthenticatedCronogramaGestaoRoute,
  AuthenticatedDesafioDiarioRoute: AuthenticatedDesafioDiarioRoute,
  AuthenticatedDocumentoSegurancaRoute: AuthenticatedDocumentoSegurancaRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFocoRoute: AuthenticatedFocoRoute,
  AuthenticatedIaBaseRoute: AuthenticatedIaBaseRoute,
  AuthenticatedIndividualRoute: AuthenticatedIndividualRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedMinhasOcorrenciasRoute: AuthenticatedMinhasOcorrenciasRoute,
  AuthenticatedModulosTreinamentoRoute: AuthenticatedModulosTreinamentoRoute,
  AuthenticatedOcorrenciasRoute: AuthenticatedOcorrenciasRoute,
  AuthenticatedOportunidadesRoute: AuthenticatedOportunidadesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedPraticoRoute: AuthenticatedPraticoRoute,
  AuthenticatedProgressoRoute: AuthenticatedProgressoRoute,
  AuthenticatedProvaRealizarRoute: AuthenticatedProvaRealizarRoute,
  AuthenticatedProvasRoute: AuthenticatedProvasRoute,
  AuthenticatedProvasCriarRoute: AuthenticatedProvasCriarRoute,
  AuthenticatedRadarAnalisesRoute: AuthenticatedRadarAnalisesRoute,
  AuthenticatedRelatorioMensalRoute: AuthenticatedRelatorioMensalRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedResumosRoute: AuthenticatedResumosRoute,
  AuthenticatedRiscoRoute: AuthenticatedRiscoRoute,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
  AuthenticatedStressTestRoute: AuthenticatedStressTestRoute,
  AuthenticatedTesteRapidoRoute: AuthenticatedTesteRapidoRoute,
  AuthenticatedTreinamentosRoute: AuthenticatedTreinamentosRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
  AuthenticatedValidarCertificadosRoute: AuthenticatedValidarCertificadosRoute,
  AuthenticatedCertificadoAttemptIdRoute:
    AuthenticatedCertificadoAttemptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
