insert into public.question_bank (bank_type, question_text, options, correct_index, correct_answer, explanation, target_sector, difficulty, theme, active)
select * from (values
('simulacoes','Durante a ronda, o vigilante identifica uma pessoa em área operacional restrita sem identificação visível. Qual deve ser a primeira conduta?', '["Abordar com segurança, interromper o avanço e confirmar autorização de acesso","Ignorar, pois a pessoa pode ser de outra empresa","Apenas fotografar e seguir a ronda","Aguardar alguém reclamar antes de agir"]'::jsonb, 0, 'Abordar com segurança, interromper o avanço e confirmar autorização de acesso', 'A prioridade é controlar o acesso e confirmar a autorização antes de permitir permanência ou deslocamento em área restrita.', 'Vigilância', 'Básico', 'Controle de Acesso', true),
('simulacoes','O operador de CFTV percebe que uma câmera crítica ficou sem imagem durante movimentação intensa na área portuária. Qual é a melhor resposta inicial?', '["Registrar a falha, comunicar imediatamente e intensificar a cobertura pelas câmeras adjacentes","Esperar a câmera voltar sozinha","Desligar as demais câmeras para reiniciar o sistema","Encerrar o monitoramento da área"]'::jsonb, 0, 'Registrar a falha, comunicar imediatamente e intensificar a cobertura pelas câmeras adjacentes', 'Uma falha em ponto crítico exige registro, comunicação e compensação operacional imediata pela cobertura disponível.', 'CFTV', 'Básico', 'Videomonitoramento', true),
('simulacoes','Um veículo chega à portaria com motorista autorizado, mas a placa do veículo não corresponde ao cadastro informado. O que fazer?', '["Suspender a liberação e validar os dados antes do acesso","Liberar porque o motorista é conhecido","Alterar o cadastro verbalmente e liberar","Permitir entrada e corrigir depois"]'::jsonb, 0, 'Suspender a liberação e validar os dados antes do acesso', 'Divergência entre credenciais e veículo exige validação antes da liberação para manter a integridade do controle de acesso.', 'Todos', 'Básico', 'Portaria', true),
('simulacoes','Durante o turno, um colaborador informa ter encontrado objeto abandonado em local incomum próximo a uma área sensível. Qual conduta é mais adequada?', '["Evitar manipulação, preservar distância, comunicar e seguir o procedimento de resposta aplicável","Abrir o objeto para identificar o proprietário","Levar o objeto até a portaria","Pedir a outro colaborador para remover do local"]'::jsonb, 0, 'Evitar manipulação, preservar distância, comunicar e seguir o procedimento de resposta aplicável', 'Objetos suspeitos não devem ser manipulados; a resposta deve priorizar isolamento, comunicação e procedimento institucional.', 'Todos', 'Intermediário', 'Objeto Suspeito', true),
('simulacoes','O CFTV observa duas pessoas tentando acessar uma área por um ponto não autorizado enquanto a equipe de campo está atendendo outra ocorrência. O que deve ocorrer?', '["Manter rastreamento visual, comunicar localização e direção, e coordenar a resposta com os recursos disponíveis","Desconsiderar porque a equipe está ocupada","Acionar apenas após perder os indivíduos de vista","Sair da central para realizar a abordagem pessoalmente"]'::jsonb, 0, 'Manter rastreamento visual, comunicar localização e direção, e coordenar a resposta com os recursos disponíveis', 'A central deve preservar consciência situacional e apoiar a equipe de campo com informação contínua e coordenação.', 'CFTV', 'Intermediário', 'Intrusão', true),
('simulacoes','Durante uma abordagem de rotina, a pessoa autorizada demonstra comportamento incompatível com o procedimento e insiste em entrar sem concluir a verificação. Qual é a melhor decisão?', '["Manter a negativa de acesso até concluir a verificação e escalar ao responsável se necessário","Liberar para evitar conflito","Permitir acesso parcial e verificar depois","Ignorar a inconsistência se a pessoa estiver uniformizada"]'::jsonb, 0, 'Manter a negativa de acesso até concluir a verificação e escalar ao responsável se necessário', 'Pressão ou urgência alegada não substituem a verificação de acesso; divergências devem ser resolvidas antes da entrada.', 'Vigilância', 'Intermediário', 'Controle de Acesso', true),
('simulacoes','Há perda simultânea de comunicação por rádio em parte da equipe durante uma ocorrência. Qual resposta reduz melhor o risco operacional?', '["Acionar o meio alternativo previsto, reorganizar a comunicação e confirmar o status dos postos afetados","Continuar a operação normalmente sem comunicação","Encerrar todos os postos imediatamente","Aguardar o fim da ocorrência para verificar os rádios"]'::jsonb, 0, 'Acionar o meio alternativo previsto, reorganizar a comunicação e confirmar o status dos postos afetados', 'Falha de comunicação durante ocorrência exige contingência imediata e confirmação da capacidade de coordenação entre postos.', 'Todos', 'Avançado', 'Comunicação Operacional', true),
('simulacoes','O operador identifica por vídeo uma situação potencialmente crítica, mas as imagens não permitem confirmar todos os detalhes. Qual deve ser a conduta?', '["Comunicar o fato como situação em verificação, informar o que é conhecido e solicitar confirmação de campo","Afirmar como fato o que parece estar acontecendo","Não comunicar até ter certeza absoluta","Compartilhar a gravação fora dos canais operacionais para pedir opinião"]'::jsonb, 0, 'Comunicar o fato como situação em verificação, informar o que é conhecido e solicitar confirmação de campo', 'A comunicação deve separar fato observado de hipótese, permitindo resposta rápida sem transmitir informação não confirmada como certeza.', 'CFTV', 'Avançado', 'Consciência Situacional', true),
('simulacoes','Em uma emergência, duas demandas críticas chegam ao mesmo tempo: uma tentativa de acesso indevido e um chamado de apoio em área operacional. Qual princípio deve orientar a priorização?', '["Avaliar risco imediato à vida, integridade da instalação e capacidade de contenção, coordenando recursos conforme a criticidade","Atender sempre a ocorrência que chegou primeiro","Escolher a ocorrência mais próxima fisicamente","Dividir a atenção sem comunicar a prioridade à equipe"]'::jsonb, 0, 'Avaliar risco imediato à vida, integridade da instalação e capacidade de contenção, coordenando recursos conforme a criticidade', 'A priorização deve ser baseada em risco e criticidade, com coordenação clara dos recursos disponíveis.', 'Todos', 'Avançado', 'Tomada de Decisão', true)
) as v(bank_type, question_text, options, correct_index, correct_answer, explanation, target_sector, difficulty, theme, active)
where not exists (
  select 1 from public.question_bank q
  where q.bank_type = 'simulacoes' and q.question_text = v.question_text
);